# dataset_path: ./datasets/ml-industry/task2/processed.csv
dataset_path: ./datasets/ml-industry/task2/processed-multilabel.csv
text_model_ckpt: bert-base-uncased
image_model_ckpt: google/vit-base-patch16-224-in21k
image_model_ckpt_2: microsoft/resnet-152
batch_size: 16
num_epoch: 3
early_stop: 5
save_strategy: 'epoch'
text_model_learning_rate: 1e-5
image_model_learning_rate: 1e-5
log_every: 1